version: "3.8"
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    volumes:
      - '~/dev/dbs-data/mysql:/var/lib/mysql'
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
  api:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ".:/app"
    depends_on:
      - db
      - phpmyadmin
    
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
   